// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package mock

import (
	"context"
	"google.golang.org/grpc"
	"mygateway/interfaces"
	"sync"
)

// Ensure, that ConnectionPoolMock does implement interfaces.ConnectionPool.
// If this is not the case, regenerate this file with moq.
var _ interfaces.ConnectionPool = &ConnectionPoolMock{}

// ConnectionPoolMock is a mock implementation of interfaces.ConnectionPool.
//
//	func TestSomethingThatUsesConnectionPool(t *testing.T) {
//
//		// make and configure a mocked interfaces.ConnectionPool
//		mockedConnectionPool := &ConnectionPoolMock{
//			CloseFunc: func() error {
//				panic("mock out the Close method")
//			},
//			GetConnectionForKeyFunc: func(ctx context.Context, key string) (*grpc.ClientConn, string, error) {
//				panic("mock out the GetConnectionForKey method")
//			},
//			GetConnectionRoundRobinFunc: func(ctx context.Context) (*grpc.ClientConn, string, error) {
//				panic("mock out the GetConnectionRoundRobin method")
//			},
//			OnBackendFailureFunc: func(key string, instanceID string)  {
//				panic("mock out the OnBackendFailure method")
//			},
//		}
//
//		// use mockedConnectionPool in code that requires interfaces.ConnectionPool
//		// and then make assertions.
//
//	}
type ConnectionPoolMock struct {
	// CloseFunc mocks the Close method.
	CloseFunc func() error

	// GetConnectionForKeyFunc mocks the GetConnectionForKey method.
	GetConnectionForKeyFunc func(ctx context.Context, key string) (*grpc.ClientConn, string, error)

	// GetConnectionRoundRobinFunc mocks the GetConnectionRoundRobin method.
	GetConnectionRoundRobinFunc func(ctx context.Context) (*grpc.ClientConn, string, error)

	// OnBackendFailureFunc mocks the OnBackendFailure method.
	OnBackendFailureFunc func(key string, instanceID string)

	// calls tracks calls to the methods.
	calls struct {
		// Close holds details about calls to the Close method.
		Close []struct {
		}
		// GetConnectionForKey holds details about calls to the GetConnectionForKey method.
		GetConnectionForKey []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Key is the key argument value.
			Key string
		}
		// GetConnectionRoundRobin holds details about calls to the GetConnectionRoundRobin method.
		GetConnectionRoundRobin []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
		}
		// OnBackendFailure holds details about calls to the OnBackendFailure method.
		OnBackendFailure []struct {
			// Key is the key argument value.
			Key string
			// InstanceID is the instanceID argument value.
			InstanceID string
		}
	}
	lockClose                   sync.RWMutex
	lockGetConnectionForKey     sync.RWMutex
	lockGetConnectionRoundRobin sync.RWMutex
	lockOnBackendFailure        sync.RWMutex
}

// Close calls CloseFunc.
func (mock *ConnectionPoolMock) Close() error {
	callInfo := struct {
	}{}
	mock.lockClose.Lock()
	mock.calls.Close = append(mock.calls.Close, callInfo)
	mock.lockClose.Unlock()
	if mock.CloseFunc == nil {
		var (
			errOut error
		)
		return errOut
	}
	return mock.CloseFunc()
}

// CloseCalls gets all the calls that were made to Close.
// Check the length with:
//
//	len(mockedConnectionPool.CloseCalls())
func (mock *ConnectionPoolMock) CloseCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockClose.RLock()
	calls = mock.calls.Close
	mock.lockClose.RUnlock()
	return calls
}

// GetConnectionForKey calls GetConnectionForKeyFunc.
func (mock *ConnectionPoolMock) GetConnectionForKey(ctx context.Context, key string) (*grpc.ClientConn, string, error) {
	callInfo := struct {
		Ctx context.Context
		Key string
	}{
		Ctx: ctx,
		Key: key,
	}
	mock.lockGetConnectionForKey.Lock()
	mock.calls.GetConnectionForKey = append(mock.calls.GetConnectionForKey, callInfo)
	mock.lockGetConnectionForKey.Unlock()
	if mock.GetConnectionForKeyFunc == nil {
		var (
			connOut       *grpc.ClientConn
			instanceIDOut string
			errOut        error
		)
		return connOut, instanceIDOut, errOut
	}
	return mock.GetConnectionForKeyFunc(ctx, key)
}

// GetConnectionForKeyCalls gets all the calls that were made to GetConnectionForKey.
// Check the length with:
//
//	len(mockedConnectionPool.GetConnectionForKeyCalls())
func (mock *ConnectionPoolMock) GetConnectionForKeyCalls() []struct {
	Ctx context.Context
	Key string
} {
	var calls []struct {
		Ctx context.Context
		Key string
	}
	mock.lockGetConnectionForKey.RLock()
	calls = mock.calls.GetConnectionForKey
	mock.lockGetConnectionForKey.RUnlock()
	return calls
}

// GetConnectionRoundRobin calls GetConnectionRoundRobinFunc.
func (mock *ConnectionPoolMock) GetConnectionRoundRobin(ctx context.Context) (*grpc.ClientConn, string, error) {
	callInfo := struct {
		Ctx context.Context
	}{
		Ctx: ctx,
	}
	mock.lockGetConnectionRoundRobin.Lock()
	mock.calls.GetConnectionRoundRobin = append(mock.calls.GetConnectionRoundRobin, callInfo)
	mock.lockGetConnectionRoundRobin.Unlock()
	if mock.GetConnectionRoundRobinFunc == nil {
		var (
			connOut       *grpc.ClientConn
			instanceIDOut string
			errOut        error
		)
		return connOut, instanceIDOut, errOut
	}
	return mock.GetConnectionRoundRobinFunc(ctx)
}

// GetConnectionRoundRobinCalls gets all the calls that were made to GetConnectionRoundRobin.
// Check the length with:
//
//	len(mockedConnectionPool.GetConnectionRoundRobinCalls())
func (mock *ConnectionPoolMock) GetConnectionRoundRobinCalls() []struct {
	Ctx context.Context
} {
	var calls []struct {
		Ctx context.Context
	}
	mock.lockGetConnectionRoundRobin.RLock()
	calls = mock.calls.GetConnectionRoundRobin
	mock.lockGetConnectionRoundRobin.RUnlock()
	return calls
}

// OnBackendFailure calls OnBackendFailureFunc.
func (mock *ConnectionPoolMock) OnBackendFailure(key string, instanceID string) {
	callInfo := struct {
		Key        string
		InstanceID string
	}{
		Key:        key,
		InstanceID: instanceID,
	}
	mock.lockOnBackendFailure.Lock()
	mock.calls.OnBackendFailure = append(mock.calls.OnBackendFailure, callInfo)
	mock.lockOnBackendFailure.Unlock()
	if mock.OnBackendFailureFunc == nil {
		return
	}
	mock.OnBackendFailureFunc(key, instanceID)
}

// OnBackendFailureCalls gets all the calls that were made to OnBackendFailure.
// Check the length with:
//
//	len(mockedConnectionPool.OnBackendFailureCalls())
func (mock *ConnectionPoolMock) OnBackendFailureCalls() []struct {
	Key        string
	InstanceID string
} {
	var calls []struct {
		Key        string
		InstanceID string
	}
	mock.lockOnBackendFailure.RLock()
	calls = mock.calls.OnBackendFailure
	mock.lockOnBackendFailure.RUnlock()
	return calls
}
