// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package mock

import (
	"context"
	"google.golang.org/grpc"
	"google.golang.org/grpc/metadata"
	"mygateway/domain"
	"mygateway/interfaces"
	"sync"
)

// Ensure, that ConnectionResolverMock does implement interfaces.ConnectionResolver.
// If this is not the case, regenerate this file with moq.
var _ interfaces.ConnectionResolver = &ConnectionResolverMock{}

// ConnectionResolverMock is a mock implementation of interfaces.ConnectionResolver.
//
//	func TestSomethingThatUsesConnectionResolver(t *testing.T) {
//
//		// make and configure a mocked interfaces.ConnectionResolver
//		mockedConnectionResolver := &ConnectionResolverMock{
//			GetConnectionFunc: func(ctx context.Context, route domain.Route, headers metadata.MD) (*grpc.ClientConn, string, string, error) {
//				panic("mock out the GetConnection method")
//			},
//			OnBackendFailureFunc: func(route domain.Route, stickyKey string, instanceID string)  {
//				panic("mock out the OnBackendFailure method")
//			},
//		}
//
//		// use mockedConnectionResolver in code that requires interfaces.ConnectionResolver
//		// and then make assertions.
//
//	}
type ConnectionResolverMock struct {
	// GetConnectionFunc mocks the GetConnection method.
	GetConnectionFunc func(ctx context.Context, route domain.Route, headers metadata.MD) (*grpc.ClientConn, string, string, error)

	// OnBackendFailureFunc mocks the OnBackendFailure method.
	OnBackendFailureFunc func(route domain.Route, stickyKey string, instanceID string)

	// calls tracks calls to the methods.
	calls struct {
		// GetConnection holds details about calls to the GetConnection method.
		GetConnection []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Route is the route argument value.
			Route domain.Route
			// Headers is the headers argument value.
			Headers metadata.MD
		}
		// OnBackendFailure holds details about calls to the OnBackendFailure method.
		OnBackendFailure []struct {
			// Route is the route argument value.
			Route domain.Route
			// StickyKey is the stickyKey argument value.
			StickyKey string
			// InstanceID is the instanceID argument value.
			InstanceID string
		}
	}
	lockGetConnection    sync.RWMutex
	lockOnBackendFailure sync.RWMutex
}

// GetConnection calls GetConnectionFunc.
func (mock *ConnectionResolverMock) GetConnection(ctx context.Context, route domain.Route, headers metadata.MD) (*grpc.ClientConn, string, string, error) {
	callInfo := struct {
		Ctx     context.Context
		Route   domain.Route
		Headers metadata.MD
	}{
		Ctx:     ctx,
		Route:   route,
		Headers: headers,
	}
	mock.lockGetConnection.Lock()
	mock.calls.GetConnection = append(mock.calls.GetConnection, callInfo)
	mock.lockGetConnection.Unlock()
	if mock.GetConnectionFunc == nil {
		var (
			clientConnOut *grpc.ClientConn
			sOut1         string
			sOut2         string
			errOut        error
		)
		return clientConnOut, sOut1, sOut2, errOut
	}
	return mock.GetConnectionFunc(ctx, route, headers)
}

// GetConnectionCalls gets all the calls that were made to GetConnection.
// Check the length with:
//
//	len(mockedConnectionResolver.GetConnectionCalls())
func (mock *ConnectionResolverMock) GetConnectionCalls() []struct {
	Ctx     context.Context
	Route   domain.Route
	Headers metadata.MD
} {
	var calls []struct {
		Ctx     context.Context
		Route   domain.Route
		Headers metadata.MD
	}
	mock.lockGetConnection.RLock()
	calls = mock.calls.GetConnection
	mock.lockGetConnection.RUnlock()
	return calls
}

// OnBackendFailure calls OnBackendFailureFunc.
func (mock *ConnectionResolverMock) OnBackendFailure(route domain.Route, stickyKey string, instanceID string) {
	callInfo := struct {
		Route      domain.Route
		StickyKey  string
		InstanceID string
	}{
		Route:      route,
		StickyKey:  stickyKey,
		InstanceID: instanceID,
	}
	mock.lockOnBackendFailure.Lock()
	mock.calls.OnBackendFailure = append(mock.calls.OnBackendFailure, callInfo)
	mock.lockOnBackendFailure.Unlock()
	if mock.OnBackendFailureFunc == nil {
		return
	}
	mock.OnBackendFailureFunc(route, stickyKey, instanceID)
}

// OnBackendFailureCalls gets all the calls that were made to OnBackendFailure.
// Check the length with:
//
//	len(mockedConnectionResolver.OnBackendFailureCalls())
func (mock *ConnectionResolverMock) OnBackendFailureCalls() []struct {
	Route      domain.Route
	StickyKey  string
	InstanceID string
} {
	var calls []struct {
		Route      domain.Route
		StickyKey  string
		InstanceID string
	}
	mock.lockOnBackendFailure.RLock()
	calls = mock.calls.OnBackendFailure
	mock.lockOnBackendFailure.RUnlock()
	return calls
}
