// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package mock

import (
	"mygateway/domain"
	"mygateway/interfaces"
	"sync"
)

// Ensure, that DiscovererMock does implement interfaces.Discoverer.
// If this is not the case, regenerate this file with moq.
var _ interfaces.Discoverer = &DiscovererMock{}

// DiscovererMock is a mock implementation of interfaces.Discoverer.
//
//	func TestSomethingThatUsesDiscoverer(t *testing.T) {
//
//		// make and configure a mocked interfaces.Discoverer
//		mockedDiscoverer := &DiscovererMock{
//			GetInstancesFunc: func() ([]domain.ServiceInstance, error) {
//				panic("mock out the GetInstances method")
//			},
//			UnregisterInstanceFunc: func(instanceID string) error {
//				panic("mock out the UnregisterInstance method")
//			},
//		}
//
//		// use mockedDiscoverer in code that requires interfaces.Discoverer
//		// and then make assertions.
//
//	}
type DiscovererMock struct {
	// GetInstancesFunc mocks the GetInstances method.
	GetInstancesFunc func() ([]domain.ServiceInstance, error)

	// UnregisterInstanceFunc mocks the UnregisterInstance method.
	UnregisterInstanceFunc func(instanceID string) error

	// calls tracks calls to the methods.
	calls struct {
		// GetInstances holds details about calls to the GetInstances method.
		GetInstances []struct {
		}
		// UnregisterInstance holds details about calls to the UnregisterInstance method.
		UnregisterInstance []struct {
			// InstanceID is the instanceID argument value.
			InstanceID string
		}
	}
	lockGetInstances       sync.RWMutex
	lockUnregisterInstance sync.RWMutex
}

// GetInstances calls GetInstancesFunc.
func (mock *DiscovererMock) GetInstances() ([]domain.ServiceInstance, error) {
	callInfo := struct {
	}{}
	mock.lockGetInstances.Lock()
	mock.calls.GetInstances = append(mock.calls.GetInstances, callInfo)
	mock.lockGetInstances.Unlock()
	if mock.GetInstancesFunc == nil {
		var (
			serviceInstancesOut []domain.ServiceInstance
			errOut              error
		)
		return serviceInstancesOut, errOut
	}
	return mock.GetInstancesFunc()
}

// GetInstancesCalls gets all the calls that were made to GetInstances.
// Check the length with:
//
//	len(mockedDiscoverer.GetInstancesCalls())
func (mock *DiscovererMock) GetInstancesCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockGetInstances.RLock()
	calls = mock.calls.GetInstances
	mock.lockGetInstances.RUnlock()
	return calls
}

// UnregisterInstance calls UnregisterInstanceFunc.
func (mock *DiscovererMock) UnregisterInstance(instanceID string) error {
	callInfo := struct {
		InstanceID string
	}{
		InstanceID: instanceID,
	}
	mock.lockUnregisterInstance.Lock()
	mock.calls.UnregisterInstance = append(mock.calls.UnregisterInstance, callInfo)
	mock.lockUnregisterInstance.Unlock()
	if mock.UnregisterInstanceFunc == nil {
		var (
			errOut error
		)
		return errOut
	}
	return mock.UnregisterInstanceFunc(instanceID)
}

// UnregisterInstanceCalls gets all the calls that were made to UnregisterInstance.
// Check the length with:
//
//	len(mockedDiscoverer.UnregisterInstanceCalls())
func (mock *DiscovererMock) UnregisterInstanceCalls() []struct {
	InstanceID string
} {
	var calls []struct {
		InstanceID string
	}
	mock.lockUnregisterInstance.RLock()
	calls = mock.calls.UnregisterInstance
	mock.lockUnregisterInstance.RUnlock()
	return calls
}
