// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package mock

import (
	"context"
	"google.golang.org/grpc/metadata"
	"mygateway/interfaces"
	"sync"
)

// Ensure, that HeaderProcessorMock does implement interfaces.HeaderProcessor.
// If this is not the case, regenerate this file with moq.
var _ interfaces.HeaderProcessor = &HeaderProcessorMock{}

// HeaderProcessorMock is a mock implementation of interfaces.HeaderProcessor.
//
//	func TestSomethingThatUsesHeaderProcessor(t *testing.T) {
//
//		// make and configure a mocked interfaces.HeaderProcessor
//		mockedHeaderProcessor := &HeaderProcessorMock{
//			ProcessFunc: func(ctx context.Context, headers metadata.MD, method string) (metadata.MD, error) {
//				panic("mock out the Process method")
//			},
//		}
//
//		// use mockedHeaderProcessor in code that requires interfaces.HeaderProcessor
//		// and then make assertions.
//
//	}
type HeaderProcessorMock struct {
	// ProcessFunc mocks the Process method.
	ProcessFunc func(ctx context.Context, headers metadata.MD, method string) (metadata.MD, error)

	// calls tracks calls to the methods.
	calls struct {
		// Process holds details about calls to the Process method.
		Process []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Headers is the headers argument value.
			Headers metadata.MD
			// Method is the method argument value.
			Method string
		}
	}
	lockProcess sync.RWMutex
}

// Process calls ProcessFunc.
func (mock *HeaderProcessorMock) Process(ctx context.Context, headers metadata.MD, method string) (metadata.MD, error) {
	callInfo := struct {
		Ctx     context.Context
		Headers metadata.MD
		Method  string
	}{
		Ctx:     ctx,
		Headers: headers,
		Method:  method,
	}
	mock.lockProcess.Lock()
	mock.calls.Process = append(mock.calls.Process, callInfo)
	mock.lockProcess.Unlock()
	if mock.ProcessFunc == nil {
		var (
			mDOut  metadata.MD
			errOut error
		)
		return mDOut, errOut
	}
	return mock.ProcessFunc(ctx, headers, method)
}

// ProcessCalls gets all the calls that were made to Process.
// Check the length with:
//
//	len(mockedHeaderProcessor.ProcessCalls())
func (mock *HeaderProcessorMock) ProcessCalls() []struct {
	Ctx     context.Context
	Headers metadata.MD
	Method  string
} {
	var calls []struct {
		Ctx     context.Context
		Headers metadata.MD
		Method  string
	}
	mock.lockProcess.RLock()
	calls = mock.calls.Process
	mock.lockProcess.RUnlock()
	return calls
}
