// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package mock

import (
	"mygateway/interfaces"
	"sync"
)

// Ensure, that JwtServiceMock does implement interfaces.JwtService.
// If this is not the case, regenerate this file with moq.
var _ interfaces.JwtService = &JwtServiceMock{}

// JwtServiceMock is a mock implementation of interfaces.JwtService.
//
//	func TestSomethingThatUsesJwtService(t *testing.T) {
//
//		// make and configure a mocked interfaces.JwtService
//		mockedJwtService := &JwtServiceMock{
//			ValidateTokenFunc: func(sessionID string, token string) (bool, error) {
//				panic("mock out the ValidateToken method")
//			},
//		}
//
//		// use mockedJwtService in code that requires interfaces.JwtService
//		// and then make assertions.
//
//	}
type JwtServiceMock struct {
	// ValidateTokenFunc mocks the ValidateToken method.
	ValidateTokenFunc func(sessionID string, token string) (bool, error)

	// calls tracks calls to the methods.
	calls struct {
		// ValidateToken holds details about calls to the ValidateToken method.
		ValidateToken []struct {
			// SessionID is the sessionID argument value.
			SessionID string
			// Token is the token argument value.
			Token string
		}
	}
	lockValidateToken sync.RWMutex
}

// ValidateToken calls ValidateTokenFunc.
func (mock *JwtServiceMock) ValidateToken(sessionID string, token string) (bool, error) {
	callInfo := struct {
		SessionID string
		Token     string
	}{
		SessionID: sessionID,
		Token:     token,
	}
	mock.lockValidateToken.Lock()
	mock.calls.ValidateToken = append(mock.calls.ValidateToken, callInfo)
	mock.lockValidateToken.Unlock()
	if mock.ValidateTokenFunc == nil {
		var (
			bOut   bool
			errOut error
		)
		return bOut, errOut
	}
	return mock.ValidateTokenFunc(sessionID, token)
}

// ValidateTokenCalls gets all the calls that were made to ValidateToken.
// Check the length with:
//
//	len(mockedJwtService.ValidateTokenCalls())
func (mock *JwtServiceMock) ValidateTokenCalls() []struct {
	SessionID string
	Token     string
} {
	var calls []struct {
		SessionID string
		Token     string
	}
	mock.lockValidateToken.RLock()
	calls = mock.calls.ValidateToken
	mock.lockValidateToken.RUnlock()
	return calls
}
