// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package mock

import (
	"mygateway/domain"
	"mygateway/interfaces"
	"sync"
)

// Ensure, that RouteMatcherMock does implement interfaces.RouteMatcher.
// If this is not the case, regenerate this file with moq.
var _ interfaces.RouteMatcher = &RouteMatcherMock{}

// RouteMatcherMock is a mock implementation of interfaces.RouteMatcher.
//
//	func TestSomethingThatUsesRouteMatcher(t *testing.T) {
//
//		// make and configure a mocked interfaces.RouteMatcher
//		mockedRouteMatcher := &RouteMatcherMock{
//			MatchFunc: func(method string) (domain.Route, bool) {
//				panic("mock out the Match method")
//			},
//		}
//
//		// use mockedRouteMatcher in code that requires interfaces.RouteMatcher
//		// and then make assertions.
//
//	}
type RouteMatcherMock struct {
	// MatchFunc mocks the Match method.
	MatchFunc func(method string) (domain.Route, bool)

	// calls tracks calls to the methods.
	calls struct {
		// Match holds details about calls to the Match method.
		Match []struct {
			// Method is the method argument value.
			Method string
		}
	}
	lockMatch sync.RWMutex
}

// Match calls MatchFunc.
func (mock *RouteMatcherMock) Match(method string) (domain.Route, bool) {
	callInfo := struct {
		Method string
	}{
		Method: method,
	}
	mock.lockMatch.Lock()
	mock.calls.Match = append(mock.calls.Match, callInfo)
	mock.lockMatch.Unlock()
	if mock.MatchFunc == nil {
		var (
			routeOut domain.Route
			bOut     bool
		)
		return routeOut, bOut
	}
	return mock.MatchFunc(method)
}

// MatchCalls gets all the calls that were made to Match.
// Check the length with:
//
//	len(mockedRouteMatcher.MatchCalls())
func (mock *RouteMatcherMock) MatchCalls() []struct {
	Method string
} {
	var calls []struct {
		Method string
	}
	mock.lockMatch.RLock()
	calls = mock.calls.Match
	mock.lockMatch.RUnlock()
	return calls
}
