// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package mock

import (
	"mygateway/interfaces"
	"sync"
	"time"
)

// Ensure, that TimeProviderMock does implement interfaces.TimeProvider.
// If this is not the case, regenerate this file with moq.
var _ interfaces.TimeProvider = &TimeProviderMock{}

// TimeProviderMock is a mock implementation of interfaces.TimeProvider.
//
//	func TestSomethingThatUsesTimeProvider(t *testing.T) {
//
//		// make and configure a mocked interfaces.TimeProvider
//		mockedTimeProvider := &TimeProviderMock{
//			NowFunc: func() time.Time {
//				panic("mock out the Now method")
//			},
//		}
//
//		// use mockedTimeProvider in code that requires interfaces.TimeProvider
//		// and then make assertions.
//
//	}
type TimeProviderMock struct {
	// NowFunc mocks the Now method.
	NowFunc func() time.Time

	// calls tracks calls to the methods.
	calls struct {
		// Now holds details about calls to the Now method.
		Now []struct {
		}
	}
	lockNow sync.RWMutex
}

// Now calls NowFunc.
func (mock *TimeProviderMock) Now() time.Time {
	callInfo := struct {
	}{}
	mock.lockNow.Lock()
	mock.calls.Now = append(mock.calls.Now, callInfo)
	mock.lockNow.Unlock()
	if mock.NowFunc == nil {
		var (
			timeOut time.Time
		)
		return timeOut
	}
	return mock.NowFunc()
}

// NowCalls gets all the calls that were made to Now.
// Check the length with:
//
//	len(mockedTimeProvider.NowCalls())
func (mock *TimeProviderMock) NowCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockNow.RLock()
	calls = mock.calls.Now
	mock.lockNow.RUnlock()
	return calls
}
