// Package handlers provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.16.2 DO NOT EDIT.
package handlers

import (
	"bytes"
	"compress/gzip"
	"context"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/labstack/echo/v4"
	"github.com/oapi-codegen/runtime"
	strictecho "github.com/oapi-codegen/runtime/strictmiddleware/echo"
)

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// List registered instances
	// (GET /v1/instances)
	GetInstances(ctx echo.Context) error
	// Register or update instance
	// (POST /v1/register)
	RegisterInstance(ctx echo.Context) error
	// Unregister instance
	// (POST /v1/unregister/{instance_id})
	UnregisterInstance(ctx echo.Context, instanceId string) error
}

// ServerInterfaceWrapper converts echo contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler ServerInterface
}

// GetInstances converts echo context to params.
func (w *ServerInterfaceWrapper) GetInstances(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetInstances(ctx)
	return err
}

// RegisterInstance converts echo context to params.
func (w *ServerInterfaceWrapper) RegisterInstance(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.RegisterInstance(ctx)
	return err
}

// UnregisterInstance converts echo context to params.
func (w *ServerInterfaceWrapper) UnregisterInstance(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "instance_id" -------------
	var instanceId string

	err = runtime.BindStyledParameterWithLocation("simple", false, "instance_id", runtime.ParamLocationPath, ctx.Param("instance_id"), &instanceId)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter instance_id: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.UnregisterInstance(ctx, instanceId)
	return err
}

// This is a simple interface which specifies echo.Route addition functions which
// are present on both echo.Echo and echo.Group, since we want to allow using
// either of them for path registration
type EchoRouter interface {
	CONNECT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	DELETE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	GET(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	HEAD(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	OPTIONS(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PATCH(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	POST(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PUT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	TRACE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
}

// RegisterHandlers adds each server route to the EchoRouter.
func RegisterHandlers(router EchoRouter, si ServerInterface) {
	RegisterHandlersWithBaseURL(router, si, "")
}

// Registers handlers, and prepends BaseURL to the paths, so that the paths
// can be served under a prefix.
func RegisterHandlersWithBaseURL(router EchoRouter, si ServerInterface, baseURL string) {

	wrapper := ServerInterfaceWrapper{
		Handler: si,
	}

	router.GET(baseURL+"/v1/instances", wrapper.GetInstances)
	router.POST(baseURL+"/v1/register", wrapper.RegisterInstance)
	router.POST(baseURL+"/v1/unregister/:instance_id", wrapper.UnregisterInstance)

}

type ErrorResponseJSONResponse struct {
	Error Err `json:"error"`
}

type GetInstancesRequestObject struct {
}

type GetInstancesResponseObject interface {
	VisitGetInstancesResponse(w http.ResponseWriter) error
}

type GetInstances200JSONResponse InstancesResponse

func (response GetInstances200JSONResponse) VisitGetInstancesResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetInstances500JSONResponse struct{ ErrorResponseJSONResponse }

func (response GetInstances500JSONResponse) VisitGetInstancesResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type RegisterInstanceRequestObject struct {
	Body *RegisterInstanceJSONRequestBody
}

type RegisterInstanceResponseObject interface {
	VisitRegisterInstanceResponse(w http.ResponseWriter) error
}

type RegisterInstance200Response struct {
}

func (response RegisterInstance200Response) VisitRegisterInstanceResponse(w http.ResponseWriter) error {
	w.WriteHeader(200)
	return nil
}

type RegisterInstance400JSONResponse struct{ ErrorResponseJSONResponse }

func (response RegisterInstance400JSONResponse) VisitRegisterInstanceResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type RegisterInstance500JSONResponse struct {
	Error Err `json:"error"`
}

func (response RegisterInstance500JSONResponse) VisitRegisterInstanceResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type UnregisterInstanceRequestObject struct {
	InstanceId string `json:"instance_id"`
}

type UnregisterInstanceResponseObject interface {
	VisitUnregisterInstanceResponse(w http.ResponseWriter) error
}

type UnregisterInstance200Response struct {
}

func (response UnregisterInstance200Response) VisitUnregisterInstanceResponse(w http.ResponseWriter) error {
	w.WriteHeader(200)
	return nil
}

type UnregisterInstance500JSONResponse struct{ ErrorResponseJSONResponse }

func (response UnregisterInstance500JSONResponse) VisitUnregisterInstanceResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {
	// List registered instances
	// (GET /v1/instances)
	GetInstances(ctx context.Context, request GetInstancesRequestObject) (GetInstancesResponseObject, error)
	// Register or update instance
	// (POST /v1/register)
	RegisterInstance(ctx context.Context, request RegisterInstanceRequestObject) (RegisterInstanceResponseObject, error)
	// Unregister instance
	// (POST /v1/unregister/{instance_id})
	UnregisterInstance(ctx context.Context, request UnregisterInstanceRequestObject) (UnregisterInstanceResponseObject, error)
}

type StrictHandlerFunc = strictecho.StrictEchoHandlerFunc
type StrictMiddlewareFunc = strictecho.StrictEchoMiddlewareFunc

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
}

// GetInstances operation middleware
func (sh *strictHandler) GetInstances(ctx echo.Context) error {
	var request GetInstancesRequestObject

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.GetInstances(ctx.Request().Context(), request.(GetInstancesRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetInstances")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(GetInstancesResponseObject); ok {
		return validResponse.VisitGetInstancesResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// RegisterInstance operation middleware
func (sh *strictHandler) RegisterInstance(ctx echo.Context) error {
	var request RegisterInstanceRequestObject

	var body RegisterInstanceJSONRequestBody
	if err := ctx.Bind(&body); err != nil {
		return err
	}
	request.Body = &body

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.RegisterInstance(ctx.Request().Context(), request.(RegisterInstanceRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "RegisterInstance")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(RegisterInstanceResponseObject); ok {
		return validResponse.VisitRegisterInstanceResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// UnregisterInstance operation middleware
func (sh *strictHandler) UnregisterInstance(ctx echo.Context, instanceId string) error {
	var request UnregisterInstanceRequestObject

	request.InstanceId = instanceId

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.UnregisterInstance(ctx.Request().Context(), request.(UnregisterInstanceRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "UnregisterInstance")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(UnregisterInstanceResponseObject); ok {
		return validResponse.VisitUnregisterInstanceResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/8RW3W7jNhN9FWK+7yIBVMvbpsBCd9tusDWQIkbWe7UxAkYa29xKJDOkVBiB3r2gRP1Z",
	"9DZZBOidRHIOZ+bMnOEzpKrQSqK0BpJnIDRaSYPNzzWRoju/4hZSJS1K6z651rlIuRVKxt+Mkm7NpAcs",
	"uPvSpDSSFS0OOhz38X/CHSTwv3i4NG6NTHxNBHUdAeFTKQgzSL56w20E9qgRElCP3zC1ULtzGZqUhHYO",
	"QAIfJGsOswM3TKVpSQ7CnfP4Pp65c6nKmtimeE3orNnrbzeWhNyDu5tbPre5bT547j3R/JgrnkEEssxz",
	"/pgjJJZKnEUTQYHG8P1ZN7rtmSd1BFZYB9yevG0RAzespLFcpriSOzW/xq1S0ZDJdooYZ0bIfY5MeDOI",
	"TrLWbTyIbA73RYqncjBmIkNpxU4ghZIpdHUVcGldXTGeZYTGhKy0Iju3WrvV/rSQFvc4L6ux8/5+D7j9",
	"TurMuBOm13Y77G9hDywXxjK16+M3Z7Nn5lA33phwL4xFwmyCIywW5t9aaUJ23YfEifjxbDJMMPg778Yd",
	"PpVobKh0PMmtw9QWEbXH2aPKjv9B7XTGP1ZEvbkOV1MEBqkSKT60O6f2n9td1uwGbrWiQGN5oeemm34r",
	"grYlIXFqgz85oyCYzR+KQB1tNjdMSFaIPBcGUyUz89rGmEQ57ZNxEL0PYZ0WZxQnVDb+xsW97OqOVYKz",
	"9e3nDYurd3HXFNG9LCUFjwzr8fMonDq6l01f9uXemH26bq361cW9hEFU/zx+FCZVFRIS+7BeQQQVkmlD",
	"eLdYOgKURsm1gAR+WSwXS5chbg8NIxNkt7BHGxIPW5I0zB6wl45Q9y+guaxN1SqDBD6hXY20YTK7f14u",
	"XzWxX6IngwIGJvDNTPXqCH5tvQiB997G02dGM7PLouB07FDPaKHle+OqdsjB1hmPC6UZ98oEs+6rRxEr",
	"tWsxxuUgO42QO0b2okLJNCdeoEUKsNAhrYZZ6eXvN6d+b0XCqRLX0+Z1L4s6XAMn6lSmKRqzK/Np711I",
	"1cj1pePt6gd4ewO2A6SMXiAd33cjtwfKzzX++RL4MkjImPrHIxvZz/kezEaMDwUCyddXzTThTjjJcA9F",
	"XrTyPJbhKcfRqFxOX4Pbl/DfK++QMMzYhSImlWU7Vcrs8k3IHKX3BST6qRpO4ESH/9hs1t2kYBcZ7niZ",
	"W/ZRpX8hsd+dlwbZQRl7CRGUlEMCB2t1EsfFMethkvfL906/Z+8vlfKcZVhhrnThuvYEJHcHHLxH2PYx",
	"vWzGcZn1qffh98RPkhLw7ftvQw8yyGG9rf8JAAD//242VW3gDQAA",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
