// Package handlers provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.16.2 DO NOT EDIT.
package handlers

import (
	"time"
)

// Err defines model for Err.
type Err struct {
	// Code Error code
	Code *string `json:"code,omitempty"`

	// Data Optional error payload
	Data *map[string]interface{} `json:"data"`

	// Message Error message
	Message *string `json:"message,omitempty"`
}

// InstanceInfo Information for a single instance
type InstanceInfo struct {
	// InstanceId Unique instance identifier
	InstanceId string `json:"instance_id"`

	// Ipv4 IPv4 address
	Ipv4 string `json:"ipv4"`

	// Port Port
	Port int `json:"port"`
}

// InstancesResponse Response with list of instances
type InstancesResponse struct {
	// Instances List of registered instances
	Instances []InstanceInfo `json:"instances"`
}

// RegisterRequest Instance registration request body
type RegisterRequest struct {
	// InstanceId Unique instance identifier
	InstanceId string `json:"instance_id"`

	// Ipv4 Instance IPv4 address
	Ipv4 string `json:"ipv4"`

	// Port Instance port
	Port int `json:"port"`

	// ServiceType Service type
	ServiceType string `json:"service_type"`

	// Timestamp Timestamp
	Timestamp time.Time `json:"timestamp"`

	// TtlMs TTL in milliseconds
	TtlMs int `json:"ttl_ms"`
}

// ErrorResponse defines model for ErrorResponse.
type ErrorResponse struct {
	Error Err `json:"error"`
}

// RegisterInstanceJSONRequestBody defines body for RegisterInstance for application/json ContentType.
type RegisterInstanceJSONRequestBody = RegisterRequest
