// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package mock

import (
	"myauth/interfaces"
	"sync"
	"time"
)

// Ensure, that JwtServiceMock does implement interfaces.JwtService.
// If this is not the case, regenerate this file with moq.
var _ interfaces.JwtService = &JwtServiceMock{}

// JwtServiceMock is a mock implementation of interfaces.JwtService.
//
//	func TestSomethingThatUsesJwtService(t *testing.T) {
//
//		// make and configure a mocked interfaces.JwtService
//		mockedJwtService := &JwtServiceMock{
//			CreateTokenFunc: func(login string, role string, sessionID string, expiresAt time.Time, issuedAt time.Time) (string, error) {
//				panic("mock out the CreateToken method")
//			},
//		}
//
//		// use mockedJwtService in code that requires interfaces.JwtService
//		// and then make assertions.
//
//	}
type JwtServiceMock struct {
	// CreateTokenFunc mocks the CreateToken method.
	CreateTokenFunc func(login string, role string, sessionID string, expiresAt time.Time, issuedAt time.Time) (string, error)

	// calls tracks calls to the methods.
	calls struct {
		// CreateToken holds details about calls to the CreateToken method.
		CreateToken []struct {
			// Login is the login argument value.
			Login string
			// Role is the role argument value.
			Role string
			// SessionID is the sessionID argument value.
			SessionID string
			// ExpiresAt is the expiresAt argument value.
			ExpiresAt time.Time
			// IssuedAt is the issuedAt argument value.
			IssuedAt time.Time
		}
	}
	lockCreateToken sync.RWMutex
}

// CreateToken calls CreateTokenFunc.
func (mock *JwtServiceMock) CreateToken(login string, role string, sessionID string, expiresAt time.Time, issuedAt time.Time) (string, error) {
	callInfo := struct {
		Login     string
		Role      string
		SessionID string
		ExpiresAt time.Time
		IssuedAt  time.Time
	}{
		Login:     login,
		Role:      role,
		SessionID: sessionID,
		ExpiresAt: expiresAt,
		IssuedAt:  issuedAt,
	}
	mock.lockCreateToken.Lock()
	mock.calls.CreateToken = append(mock.calls.CreateToken, callInfo)
	mock.lockCreateToken.Unlock()
	if mock.CreateTokenFunc == nil {
		var (
			sOut   string
			errOut error
		)
		return sOut, errOut
	}
	return mock.CreateTokenFunc(login, role, sessionID, expiresAt, issuedAt)
}

// CreateTokenCalls gets all the calls that were made to CreateToken.
// Check the length with:
//
//	len(mockedJwtService.CreateTokenCalls())
func (mock *JwtServiceMock) CreateTokenCalls() []struct {
	Login     string
	Role      string
	SessionID string
	ExpiresAt time.Time
	IssuedAt  time.Time
} {
	var calls []struct {
		Login     string
		Role      string
		SessionID string
		ExpiresAt time.Time
		IssuedAt  time.Time
	}
	mock.lockCreateToken.RLock()
	calls = mock.calls.CreateToken
	mock.lockCreateToken.RUnlock()
	return calls
}
