// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package mock

import (
	"context"
	"myauth/domain"
	"myauth/interfaces"
	"sync"
)

// Ensure, that UserStoreMock does implement interfaces.UserStore.
// If this is not the case, regenerate this file with moq.
var _ interfaces.UserStore = &UserStoreMock{}

// UserStoreMock is a mock implementation of interfaces.UserStore.
//
//	func TestSomethingThatUsesUserStore(t *testing.T) {
//
//		// make and configure a mocked interfaces.UserStore
//		mockedUserStore := &UserStoreMock{
//			GetByLoginFunc: func(ctx context.Context, login string) (domain.User, error) {
//				panic("mock out the GetByLogin method")
//			},
//		}
//
//		// use mockedUserStore in code that requires interfaces.UserStore
//		// and then make assertions.
//
//	}
type UserStoreMock struct {
	// GetByLoginFunc mocks the GetByLogin method.
	GetByLoginFunc func(ctx context.Context, login string) (domain.User, error)

	// calls tracks calls to the methods.
	calls struct {
		// GetByLogin holds details about calls to the GetByLogin method.
		GetByLogin []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Login is the login argument value.
			Login string
		}
	}
	lockGetByLogin sync.RWMutex
}

// GetByLogin calls GetByLoginFunc.
func (mock *UserStoreMock) GetByLogin(ctx context.Context, login string) (domain.User, error) {
	callInfo := struct {
		Ctx   context.Context
		Login string
	}{
		Ctx:   ctx,
		Login: login,
	}
	mock.lockGetByLogin.Lock()
	mock.calls.GetByLogin = append(mock.calls.GetByLogin, callInfo)
	mock.lockGetByLogin.Unlock()
	if mock.GetByLoginFunc == nil {
		var (
			userOut domain.User
			errOut  error
		)
		return userOut, errOut
	}
	return mock.GetByLoginFunc(ctx, login)
}

// GetByLoginCalls gets all the calls that were made to GetByLogin.
// Check the length with:
//
//	len(mockedUserStore.GetByLoginCalls())
func (mock *UserStoreMock) GetByLoginCalls() []struct {
	Ctx   context.Context
	Login string
} {
	var calls []struct {
		Ctx   context.Context
		Login string
	}
	mock.lockGetByLogin.RLock()
	calls = mock.calls.GetByLogin
	mock.lockGetByLogin.RUnlock()
	return calls
}
