// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.2
// source: api/Api.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type LoginRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"` // mandatory, must not be empty
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	SessionId     string                 `protobuf:"bytes,3,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"` // mandatory, must not be empty
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginRequest) Reset() {
	*x = LoginRequest{}
	mi := &file_api_Api_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginRequest) ProtoMessage() {}

func (x *LoginRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_Api_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginRequest.ProtoReflect.Descriptor instead.
func (*LoginRequest) Descriptor() ([]byte, []int) {
	return file_api_Api_proto_rawDescGZIP(), []int{0}
}

func (x *LoginRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *LoginRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *LoginRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

type LoginResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`                          // JWT for MyServiceAPI.MyService* api access
	ExpiresAt     *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"` // token expiration time
	Role          string                 `protobuf:"bytes,3,opt,name=role,proto3" json:"role,omitempty"`                            // user role
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginResponse) Reset() {
	*x = LoginResponse{}
	mi := &file_api_Api_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginResponse) ProtoMessage() {}

func (x *LoginResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_Api_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginResponse.ProtoReflect.Descriptor instead.
func (*LoginResponse) Descriptor() ([]byte, []int) {
	return file_api_Api_proto_rawDescGZIP(), []int{1}
}

func (x *LoginResponse) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *LoginResponse) GetExpiresAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ExpiresAt
	}
	return nil
}

func (x *LoginResponse) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

type EchoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         string                 `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EchoRequest) Reset() {
	*x = EchoRequest{}
	mi := &file_api_Api_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EchoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EchoRequest) ProtoMessage() {}

func (x *EchoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_Api_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EchoRequest.ProtoReflect.Descriptor instead.
func (*EchoRequest) Descriptor() ([]byte, []int) {
	return file_api_Api_proto_rawDescGZIP(), []int{2}
}

func (x *EchoRequest) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type EchoResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ClientValue     string                 `protobuf:"bytes,1,opt,name=client_value,json=clientValue,proto3" json:"client_value,omitempty"`
	ServerValue     string                 `protobuf:"bytes,2,opt,name=server_value,json=serverValue,proto3" json:"server_value,omitempty"`
	PodName         string                 `protobuf:"bytes,3,opt,name=pod_name,json=podName,proto3" json:"pod_name,omitempty"`
	ServerSessionId string                 `protobuf:"bytes,4,opt,name=server_session_id,json=serverSessionId,proto3" json:"server_session_id,omitempty"`
	ClientSessionId string                 `protobuf:"bytes,5,opt,name=client_session_id,json=clientSessionId,proto3" json:"client_session_id,omitempty"`
	Index           int32                  `protobuf:"varint,6,opt,name=index,proto3" json:"index,omitempty"`
	ServerMethod    string                 `protobuf:"bytes,7,opt,name=server_method,json=serverMethod,proto3" json:"server_method,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *EchoResponse) Reset() {
	*x = EchoResponse{}
	mi := &file_api_Api_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EchoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EchoResponse) ProtoMessage() {}

func (x *EchoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_Api_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EchoResponse.ProtoReflect.Descriptor instead.
func (*EchoResponse) Descriptor() ([]byte, []int) {
	return file_api_Api_proto_rawDescGZIP(), []int{3}
}

func (x *EchoResponse) GetClientValue() string {
	if x != nil {
		return x.ClientValue
	}
	return ""
}

func (x *EchoResponse) GetServerValue() string {
	if x != nil {
		return x.ServerValue
	}
	return ""
}

func (x *EchoResponse) GetPodName() string {
	if x != nil {
		return x.PodName
	}
	return ""
}

func (x *EchoResponse) GetServerSessionId() string {
	if x != nil {
		return x.ServerSessionId
	}
	return ""
}

func (x *EchoResponse) GetClientSessionId() string {
	if x != nil {
		return x.ClientSessionId
	}
	return ""
}

func (x *EchoResponse) GetIndex() int32 {
	if x != nil {
		return x.Index
	}
	return 0
}

func (x *EchoResponse) GetServerMethod() string {
	if x != nil {
		return x.ServerMethod
	}
	return ""
}

type ShutdownRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShutdownRequest) Reset() {
	*x = ShutdownRequest{}
	mi := &file_api_Api_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShutdownRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShutdownRequest) ProtoMessage() {}

func (x *ShutdownRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_Api_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShutdownRequest.ProtoReflect.Descriptor instead.
func (*ShutdownRequest) Descriptor() ([]byte, []int) {
	return file_api_Api_proto_rawDescGZIP(), []int{4}
}

type ShutdownResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	PodName         string                 `protobuf:"bytes,1,opt,name=pod_name,json=podName,proto3" json:"pod_name,omitempty"`
	ServerSessionId string                 `protobuf:"bytes,2,opt,name=server_session_id,json=serverSessionId,proto3" json:"server_session_id,omitempty"`
	ClientSessionId string                 `protobuf:"bytes,3,opt,name=client_session_id,json=clientSessionId,proto3" json:"client_session_id,omitempty"`
	Index           int32                  `protobuf:"varint,4,opt,name=index,proto3" json:"index,omitempty"`
	ServerMethod    string                 `protobuf:"bytes,5,opt,name=server_method,json=serverMethod,proto3" json:"server_method,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ShutdownResponse) Reset() {
	*x = ShutdownResponse{}
	mi := &file_api_Api_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShutdownResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShutdownResponse) ProtoMessage() {}

func (x *ShutdownResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_Api_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShutdownResponse.ProtoReflect.Descriptor instead.
func (*ShutdownResponse) Descriptor() ([]byte, []int) {
	return file_api_Api_proto_rawDescGZIP(), []int{5}
}

func (x *ShutdownResponse) GetPodName() string {
	if x != nil {
		return x.PodName
	}
	return ""
}

func (x *ShutdownResponse) GetServerSessionId() string {
	if x != nil {
		return x.ServerSessionId
	}
	return ""
}

func (x *ShutdownResponse) GetClientSessionId() string {
	if x != nil {
		return x.ClientSessionId
	}
	return ""
}

func (x *ShutdownResponse) GetIndex() int32 {
	if x != nil {
		return x.Index
	}
	return 0
}

func (x *ShutdownResponse) GetServerMethod() string {
	if x != nil {
		return x.ServerMethod
	}
	return ""
}

var File_api_Api_proto protoreflect.FileDescriptor

const file_api_Api_proto_rawDesc = "" +
	"\n" +
	"\rapi/Api.proto\x12\n" +
	"my_service\x1a\x1fgoogle/protobuf/timestamp.proto\"e\n" +
	"\fLoginRequest\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\x12\x1d\n" +
	"\n" +
	"session_id\x18\x03 \x01(\tR\tsessionId\"t\n" +
	"\rLoginResponse\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\x129\n" +
	"\n" +
	"expires_at\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\texpiresAt\x12\x12\n" +
	"\x04role\x18\x03 \x01(\tR\x04role\"#\n" +
	"\vEchoRequest\x12\x14\n" +
	"\x05value\x18\x01 \x01(\tR\x05value\"\x82\x02\n" +
	"\fEchoResponse\x12!\n" +
	"\fclient_value\x18\x01 \x01(\tR\vclientValue\x12!\n" +
	"\fserver_value\x18\x02 \x01(\tR\vserverValue\x12\x19\n" +
	"\bpod_name\x18\x03 \x01(\tR\apodName\x12*\n" +
	"\x11server_session_id\x18\x04 \x01(\tR\x0fserverSessionId\x12*\n" +
	"\x11client_session_id\x18\x05 \x01(\tR\x0fclientSessionId\x12\x14\n" +
	"\x05index\x18\x06 \x01(\x05R\x05index\x12#\n" +
	"\rserver_method\x18\a \x01(\tR\fserverMethod\"\x11\n" +
	"\x0fShutdownRequest\"\xc0\x01\n" +
	"\x10ShutdownResponse\x12\x19\n" +
	"\bpod_name\x18\x01 \x01(\tR\apodName\x12*\n" +
	"\x11server_session_id\x18\x02 \x01(\tR\x0fserverSessionId\x12*\n" +
	"\x11client_session_id\x18\x03 \x01(\tR\x0fclientSessionId\x12\x14\n" +
	"\x05index\x18\x04 \x01(\x05R\x05index\x12#\n" +
	"\rserver_method\x18\x05 \x01(\tR\fserverMethod2\xab\x02\n" +
	"\fMyServiceAPI\x12<\n" +
	"\x05Login\x12\x18.my_service.LoginRequest\x1a\x19.my_service.LoginResponse\x12B\n" +
	"\rMyServiceEcho\x12\x17.my_service.EchoRequest\x1a\x18.my_service.EchoResponse\x12I\n" +
	"\x12MyServiceSubscribe\x12\x17.my_service.EchoRequest\x1a\x18.my_service.EchoResponse0\x01\x12N\n" +
	"\x11MyServiceShutdown\x12\x1b.my_service.ShutdownRequest\x1a\x1c.my_service.ShutdownResponseB\x1fZ\x13integrationtests/pb\xaa\x02\aMyProtob\x06proto3"

var (
	file_api_Api_proto_rawDescOnce sync.Once
	file_api_Api_proto_rawDescData []byte
)

func file_api_Api_proto_rawDescGZIP() []byte {
	file_api_Api_proto_rawDescOnce.Do(func() {
		file_api_Api_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_Api_proto_rawDesc), len(file_api_Api_proto_rawDesc)))
	})
	return file_api_Api_proto_rawDescData
}

var file_api_Api_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_api_Api_proto_goTypes = []any{
	(*LoginRequest)(nil),          // 0: my_service.LoginRequest
	(*LoginResponse)(nil),         // 1: my_service.LoginResponse
	(*EchoRequest)(nil),           // 2: my_service.EchoRequest
	(*EchoResponse)(nil),          // 3: my_service.EchoResponse
	(*ShutdownRequest)(nil),       // 4: my_service.ShutdownRequest
	(*ShutdownResponse)(nil),      // 5: my_service.ShutdownResponse
	(*timestamppb.Timestamp)(nil), // 6: google.protobuf.Timestamp
}
var file_api_Api_proto_depIdxs = []int32{
	6, // 0: my_service.LoginResponse.expires_at:type_name -> google.protobuf.Timestamp
	0, // 1: my_service.MyServiceAPI.Login:input_type -> my_service.LoginRequest
	2, // 2: my_service.MyServiceAPI.MyServiceEcho:input_type -> my_service.EchoRequest
	2, // 3: my_service.MyServiceAPI.MyServiceSubscribe:input_type -> my_service.EchoRequest
	4, // 4: my_service.MyServiceAPI.MyServiceShutdown:input_type -> my_service.ShutdownRequest
	1, // 5: my_service.MyServiceAPI.Login:output_type -> my_service.LoginResponse
	3, // 6: my_service.MyServiceAPI.MyServiceEcho:output_type -> my_service.EchoResponse
	3, // 7: my_service.MyServiceAPI.MyServiceSubscribe:output_type -> my_service.EchoResponse
	5, // 8: my_service.MyServiceAPI.MyServiceShutdown:output_type -> my_service.ShutdownResponse
	5, // [5:9] is the sub-list for method output_type
	1, // [1:5] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_api_Api_proto_init() }
func file_api_Api_proto_init() {
	if File_api_Api_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_Api_proto_rawDesc), len(file_api_Api_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_Api_proto_goTypes,
		DependencyIndexes: file_api_Api_proto_depIdxs,
		MessageInfos:      file_api_Api_proto_msgTypes,
	}.Build()
	File_api_Api_proto = out.File
	file_api_Api_proto_goTypes = nil
	file_api_Api_proto_depIdxs = nil
}
