// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v6.33.2
// source: api/Api.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	MyServiceAPI_Login_FullMethodName              = "/my_service.MyServiceAPI/Login"
	MyServiceAPI_MyServiceEcho_FullMethodName      = "/my_service.MyServiceAPI/MyServiceEcho"
	MyServiceAPI_MyServiceSubscribe_FullMethodName = "/my_service.MyServiceAPI/MyServiceSubscribe"
	MyServiceAPI_MyServiceShutdown_FullMethodName  = "/my_service.MyServiceAPI/MyServiceShutdown"
)

// MyServiceAPIClient is the client API for MyServiceAPI service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MyServiceAPIClient interface {
	Login(ctx context.Context, in *LoginRequest, opts ...grpc.CallOption) (*LoginResponse, error)
	MyServiceEcho(ctx context.Context, in *EchoRequest, opts ...grpc.CallOption) (*EchoResponse, error)
	MyServiceSubscribe(ctx context.Context, in *EchoRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[EchoResponse], error)
	MyServiceShutdown(ctx context.Context, in *ShutdownRequest, opts ...grpc.CallOption) (*ShutdownResponse, error)
}

type myServiceAPIClient struct {
	cc grpc.ClientConnInterface
}

func NewMyServiceAPIClient(cc grpc.ClientConnInterface) MyServiceAPIClient {
	return &myServiceAPIClient{cc}
}

func (c *myServiceAPIClient) Login(ctx context.Context, in *LoginRequest, opts ...grpc.CallOption) (*LoginResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LoginResponse)
	err := c.cc.Invoke(ctx, MyServiceAPI_Login_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *myServiceAPIClient) MyServiceEcho(ctx context.Context, in *EchoRequest, opts ...grpc.CallOption) (*EchoResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EchoResponse)
	err := c.cc.Invoke(ctx, MyServiceAPI_MyServiceEcho_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *myServiceAPIClient) MyServiceSubscribe(ctx context.Context, in *EchoRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[EchoResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &MyServiceAPI_ServiceDesc.Streams[0], MyServiceAPI_MyServiceSubscribe_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[EchoRequest, EchoResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type MyServiceAPI_MyServiceSubscribeClient = grpc.ServerStreamingClient[EchoResponse]

func (c *myServiceAPIClient) MyServiceShutdown(ctx context.Context, in *ShutdownRequest, opts ...grpc.CallOption) (*ShutdownResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ShutdownResponse)
	err := c.cc.Invoke(ctx, MyServiceAPI_MyServiceShutdown_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MyServiceAPIServer is the server API for MyServiceAPI service.
// All implementations must embed UnimplementedMyServiceAPIServer
// for forward compatibility.
type MyServiceAPIServer interface {
	Login(context.Context, *LoginRequest) (*LoginResponse, error)
	MyServiceEcho(context.Context, *EchoRequest) (*EchoResponse, error)
	MyServiceSubscribe(*EchoRequest, grpc.ServerStreamingServer[EchoResponse]) error
	MyServiceShutdown(context.Context, *ShutdownRequest) (*ShutdownResponse, error)
	mustEmbedUnimplementedMyServiceAPIServer()
}

// UnimplementedMyServiceAPIServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedMyServiceAPIServer struct{}

func (UnimplementedMyServiceAPIServer) Login(context.Context, *LoginRequest) (*LoginResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Login not implemented")
}
func (UnimplementedMyServiceAPIServer) MyServiceEcho(context.Context, *EchoRequest) (*EchoResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method MyServiceEcho not implemented")
}
func (UnimplementedMyServiceAPIServer) MyServiceSubscribe(*EchoRequest, grpc.ServerStreamingServer[EchoResponse]) error {
	return status.Error(codes.Unimplemented, "method MyServiceSubscribe not implemented")
}
func (UnimplementedMyServiceAPIServer) MyServiceShutdown(context.Context, *ShutdownRequest) (*ShutdownResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method MyServiceShutdown not implemented")
}
func (UnimplementedMyServiceAPIServer) mustEmbedUnimplementedMyServiceAPIServer() {}
func (UnimplementedMyServiceAPIServer) testEmbeddedByValue()                      {}

// UnsafeMyServiceAPIServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MyServiceAPIServer will
// result in compilation errors.
type UnsafeMyServiceAPIServer interface {
	mustEmbedUnimplementedMyServiceAPIServer()
}

func RegisterMyServiceAPIServer(s grpc.ServiceRegistrar, srv MyServiceAPIServer) {
	// If the following call panics, it indicates UnimplementedMyServiceAPIServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&MyServiceAPI_ServiceDesc, srv)
}

func _MyServiceAPI_Login_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LoginRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MyServiceAPIServer).Login(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MyServiceAPI_Login_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MyServiceAPIServer).Login(ctx, req.(*LoginRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MyServiceAPI_MyServiceEcho_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EchoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MyServiceAPIServer).MyServiceEcho(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MyServiceAPI_MyServiceEcho_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MyServiceAPIServer).MyServiceEcho(ctx, req.(*EchoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MyServiceAPI_MyServiceSubscribe_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(EchoRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(MyServiceAPIServer).MyServiceSubscribe(m, &grpc.GenericServerStream[EchoRequest, EchoResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type MyServiceAPI_MyServiceSubscribeServer = grpc.ServerStreamingServer[EchoResponse]

func _MyServiceAPI_MyServiceShutdown_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ShutdownRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MyServiceAPIServer).MyServiceShutdown(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MyServiceAPI_MyServiceShutdown_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MyServiceAPIServer).MyServiceShutdown(ctx, req.(*ShutdownRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// MyServiceAPI_ServiceDesc is the grpc.ServiceDesc for MyServiceAPI service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MyServiceAPI_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "my_service.MyServiceAPI",
	HandlerType: (*MyServiceAPIServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Login",
			Handler:    _MyServiceAPI_Login_Handler,
		},
		{
			MethodName: "MyServiceEcho",
			Handler:    _MyServiceAPI_MyServiceEcho_Handler,
		},
		{
			MethodName: "MyServiceShutdown",
			Handler:    _MyServiceAPI_MyServiceShutdown_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "MyServiceSubscribe",
			Handler:       _MyServiceAPI_MyServiceSubscribe_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "api/Api.proto",
}
